name:  CI test

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: DIR
      run:  dir *.*   
    
    - name: Archive artifacts
      run:  zip --version
