name:  CI test

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: download latest PBL
      shell: pwsh
      env:   
         PBL_URI: ${{ secrets.LETEST_PBL_URI }}
         ACCESS_KEY: ${{ secrets.JFROG_TOKEN }}
      run:   Invoke-WebRequest -Uri $env:PBL_URI -OutFile "pbl.zip" -Headers @{ "Authorization" = $env:ACCESS_KEY}


    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: DIR
      run:  dir *.*   
    
    - name:  Archive artifacts
      shell: pwsh
      run:   Compress-Archive -Path *.* -DestinationPath artifact.zip
      
    - name: DIR2
      run:  dir *.*   

    - uses: actions/upload-artifact@v1
      with:
         name: Upload artifacts
         path: artifact.zip
